/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import javax.swing.JPanel;
import viewer.setting.PreferencesPane;

/**
 * <p>JFrame responsabile della visualizzazione e modifica delle enventuali 
 * Preferences dell'applicazione. </p>
 * @author Nicola Preden, matricola 818578, Facoltà di informatica Ca' Foscari
 * in Venice
 */
public class PreferenceWindow extends javax.swing.JFrame {

    private class JPanelLanguages extends JPanel implements PreferencesPane {        

        @Override
        public void savePreferences() {
            throw new UnsupportedOperationException("Not supported yet.");
        }

        @Override
        public void resetToDefaultPreferences() {
            throw new UnsupportedOperationException("Not supported yet.");
        }

        @Override
        public boolean isModified() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
    private class JPanelTextGraphics extends JPanel implements PreferencesPane {       

        @Override
        public void savePreferences() {
            throw new UnsupportedOperationException("Not supported yet.");
        }

        @Override
        public void resetToDefaultPreferences() {
            throw new UnsupportedOperationException("Not supported yet.");
        }

        @Override
        public boolean isModified() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
    /**
     * Creates new form PreferenceWindow
     */
    public PreferenceWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTP_Preferences = new javax.swing.JTabbedPane();
        jP_TextLayout = new JPanelTextGraphics();
        jP_Languages = new JPanelLanguages();
        jB_close = new javax.swing.JButton();
        jB_CloseAndSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preferenze");

        org.jdesktop.layout.GroupLayout jP_TextLayoutLayout = new org.jdesktop.layout.GroupLayout(jP_TextLayout);
        jP_TextLayout.setLayout(jP_TextLayoutLayout);
        jP_TextLayoutLayout.setHorizontalGroup(
            jP_TextLayoutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 596, Short.MAX_VALUE)
        );
        jP_TextLayoutLayout.setVerticalGroup(
            jP_TextLayoutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 304, Short.MAX_VALUE)
        );

        jTP_Preferences.addTab("Layout Testo", jP_TextLayout);

        org.jdesktop.layout.GroupLayout jP_LanguagesLayout = new org.jdesktop.layout.GroupLayout(jP_Languages);
        jP_Languages.setLayout(jP_LanguagesLayout);
        jP_LanguagesLayout.setHorizontalGroup(
            jP_LanguagesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 596, Short.MAX_VALUE)
        );
        jP_LanguagesLayout.setVerticalGroup(
            jP_LanguagesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 304, Short.MAX_VALUE)
        );

        jTP_Preferences.addTab("Lingue", jP_Languages);

        jB_close.setText("Chiudi");
        jB_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_closeActionPerformed(evt);
            }
        });

        jB_CloseAndSave.setText("Salva");
        jB_CloseAndSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CloseAndSaveActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTP_Preferences)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jB_CloseAndSave)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jB_close)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTP_Preferences)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jB_CloseAndSave)
                    .add(jB_close))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jB_closeActionPerformed

    private void jB_CloseAndSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CloseAndSaveActionPerformed
        // TODO add your handling code here:
        JPanelLanguages lang = (JPanelLanguages)jP_Languages;
        JPanelTextGraphics text = (JPanelTextGraphics)jP_TextLayout;
        if (lang.isModified()) {
            lang.savePreferences();
        }
        if (text.isModified()) {
            text.savePreferences();
        }
    }//GEN-LAST:event_jB_CloseAndSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_CloseAndSave;
    private javax.swing.JButton jB_close;
    private javax.swing.JPanel jP_Languages;
    private javax.swing.JPanel jP_TextLayout;
    private javax.swing.JTabbedPane jTP_Preferences;
    // End of variables declaration//GEN-END:variables
}
